export const menuLinks = [
  {
    to: '/products/laptops',
    title: 'Laptops and PC',
  },
  {
    to: '/products/phones',
    title: 'Cellphones, TV, and Electronics',
  },
  {
    to: '/products/gamers',
    title: 'For Gamers',
  },
  {
    to: '/products/household_appliances',
    title: 'Household Appliances',
  },
  {
    to: '/products/household_goods',
    title: 'Household Goods',
  },
  {
    to: '/products/tools_and_auto',
    title: 'Tools and Autogoods',
  },
  {
    to: '/products/blumbing_repair',
    title: 'Blumbing and Repair',
  },
  {
    to: '/products/sports_hobbies',
    title: 'Sport and Hobbies',
  },
  {
    to: '/products/children',
    title: 'Goods For Children',
  },
  {
    to: '/products/clothes',
    title: 'Clothes, Footwear, and Accessories',
  },
  {
    to: '/products/office',
    title: 'Office, School, and Books',
  },
  {
    to: '/products/health',
    title: 'Health and Beauty',
  },
  {
    to: '/products/food',
    title: 'Food and Alcohol',
  },
];

export const pageLinks = [
  {
    to: '/about',
    title: 'About',
  },
  {
    to: '/contacts',
    title: 'Contacts',
  },
  {
    to: '/careers',
    title: 'Careers',
  },
  {
    to: '/shipment-and-payment',
    title: 'Shipment and Payment',
  },
  {
    to: '/partnership',
    title: 'Become a Partner',
  },
  {
    to: '/legal',
    title: 'Legal Information',
  },
];

export const footerLinks = {
  estore: [
    {
      to: '/about',
      title: 'About',
    },
    {
      to: '/contacts',
      title: 'Contacts',
    },
    {
      to: '/careers',
      title: 'Careers',
    },
    {
      to: '/partnership',
      title: 'Become a Partner',
    },
    {
      to: '/trade-in',
      title: 'Trade-In',
    },
    {
      to: '/legal-info',
      title: 'Legal Information',
    },
    {
      to: '/network',
      title: 'Network',
    },
  ],
  forCustomers: [
    {
      to: '/shipment-and-payment',
      title: 'Shipment and Payment',
    },
    {
      to: '/return-order',
      title: 'Return the Order',
    },
    {
      to: '/manuals',
      title: 'Manuals',
    },
    {
      to: '/promotions',
      title: 'Sales and Promotions',
    },
    {
      to: '/credit',
      title: 'Credit',
    },
    {
      to: '/popular',
      title: 'Popular Products',
    },
  ],
  shops: [
    {
      to: '/shops/ukraine',
      title: 'Ukraine',
    },
    {
      to: '/shops/poland',
      title: 'Poland',
    },
    {
      to: '/shops/germany',
      title: 'Germany',
    },
    {
      to: '/shops/lithuania',
      title: 'Lithuania',
    },
    {
      to: '/shops/latvia',
      title: 'Latvia',
    },
    {
      to: '/shops/estonia',
      title: 'Estonia',
    },
  ],
};

export const products = [
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion: ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion: ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion: ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion: ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion: ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ]
  },
  {
    title: 'Apple IPhone 13 Pro Max 256Gb Sierra Blue',
    price: '1199',
    color: '#49A2DA',
    rating: 5,
    image: 'https://content1.rozetka.com.ua/goods/images/big/221208453.jpg',
    promotion:  ['-10%', 'Top'],
    isInStock: true,
    shortInfo: 'Screen (6.1”, OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / main camera: 12Mp + 12Mp + 12Mp, front camera: 12Mp / storage: 128Gb / 3G / LTE / 5G / GPS / Nano-SIM / iOS 15',
    description: 'iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes. Privacy is built in. iPhone helps put you in control of your personal information. For example, when you\'re browsing, Safari intelligently helps block trackers from profiling you and shows you which ones have been blocked in your Privacy Report. And the list goes on. Everything just works. Our hardware and software work together seamlessly. Want to pair new AirPods with your iPhone? It\'s a simple one‑tap setup. See a phone number in a photo? Live Text lets you tap it to make the call. You can also copy text, send an email, or look up directions right from the photo.',
    reviews: [
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
      {
        user: {
          firstName: 'Jack',
          lastName: 'Sparrow',
          email: 'j.sparrow@gmail.com',
          phone: '+380443821628',
          city: 'Kyiv',
          language: 'ua',
          avatarUrl: 'https://images0.persgroep.net/rcs/TsQxXQilRP4tP-zJDE8Z-IhmbBQ/diocontent/16912262/_crop/153/150/2566/1450/_fitwidth/694/?appId=21791a8992982cd8da851550a453bd7f&quality=0.8',
          orders: [],
        },
        comment: 'That new IPhone 13 Pro Max is amazing! I\'m so excited about that. Really cool thing. Higly recommend.',
        likes: 3,
        dislikes: 1,
        date: 'Aug 13, 2022',
      },
    ],
  },
];